name: bodygoal
description: "Your Body. Your Goal. Your Pace. BodyGoal is made for you."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter 

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  get_it_mixin: ^4.2.2
  intl: 0.19.0
  internet_connection_checker: ^3.0.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  sized_context: ^1.0.0+4
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  rate_my_app: ^2.3.1
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  gif: ^2.3.0
  retrofit: ^4.4.2
  hexcolor: ^3.0.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  video_player: ^2.9.5
  desktop_window: ^0.4.2
  flutter_animate: ^4.5.2
  flutter_displaymode: ^0.6.0
  get_it: ^7.7.0
  gap: ^3.0.1
  go_router: ^15.1.1
  json_annotation: ^4.9.0
  analyzer: ^6.7.0
  share_plus: ^11.0.0
  flutter_inappwebview: ^6.1.5
  firebase_crashlytics: ^4.3.5
  logger: ^2.5.0
  flutter_spinkit: ^5.2.1
  app_links: ^6.4.0
  firebase_remote_config: ^5.4.3
  firebase_analytics: ^11.4.5
  upgrader: ^11.3.1
  live_activities: ^2.3.2
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  dependency_validator: ^4.1.3
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/images/_common/
    - assets/images/icons/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
